theme: jekyll-theme-cayman
title: Welcome to Bharat's [homepage](index.md).
description: Using the climate data from multiple models and observations, investigating potential extreme events in carbon fluxes (plant productivity), due to human induced fossil fuel emissions and land use and land cover changes, and their attribution to climate drivers.
